name: "🚀 publish"

on:
    push:
        branches: 
        - Tos

jobs:
    release:
        name: 🚀 publish
        runs-on: ubuntu-latest
        steps:
            - name: 📚 checkout
              uses: actions/checkout@v3.4.0
            - name: 🟢 node
              uses: actions/setup-node@v3.6.0
              with:
                  node-version: 12
                  registry-url: https://registry.npmjs.org
            - name: 🚀 publish
              run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
